---
- name: Configure the web server
  ansible.builtin.import_tasks: configure-web.yml

- name: Configure Icingaweb2
  ansible.builtin.import_tasks: configure-icingaweb2.yml

- name: Configure Users
  ansible.builtin.import_tasks: configure-users.yml

- name: Configure the Monitoring module
  ansible.builtin.import_tasks: configure-monitoring.yml
