---
# - name: Set default fact for mysql command
#  ansible.builtin.set_fact:
#  tags: ['install-icinga2-stack', 'install-icinga2-ido']
#    _mysql_cmd: 'mysql'

- name: Set fact for mysql command if auth params are given
  ansible.builtin.set_fact:
    _mysql_cmd: 'mysql -h {{ icingaweb2_ido_db_host }} -u{{ icingaweb2_ido_db_user }} -p{{ icingaweb2_ido_db_password }}'
